version: 3.2.0.{build}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
build_script:
- ps: ./bootbuild.ps1
artifacts:
- path: ./artifacts/*.nupkg
  name: NuGet